export default [
	{
		title: "Strange Specialized Killstreak Australium Axtinguisher (strange parts)",
		input: {
			name: "Axtinguisher",
			fullName: "Strange Specialized Killstreak Australium Axtinguisher",
			id: "12507393354",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUwYJSRLsvy1Km8DjH82cEfIPpN066ZRq1Td5lgQ1MrDhZmAyKgfHU_cLX6NtrAy8W3Bnup4zVdPur-heew3otoTCZ7R_ZcYMQZeUvB7w1w/",
			tradable: true,
			craftable: true,
			quality: 11,
			australium: true,
			killstreak: 2,
			defindex: 38,
			level: -1,
			classes: ["Pyro"],
			type: "melee",
			sheen: "Team Shine",
			parts: ["Heavies Killed", "Point Blank Kills"],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 38,
			quality: 11,
			name: "Axtinguisher",
			id: "12507393354",
			killstreak: 2,
			killstreak_sheen: 1,
			australium: true,
			strange_parts: [14, 85],
		},
	},
	{
		title: "Strange Festivized Specialized Killstreak Flower Power Scattergun (Well-Worn)",
		input: {
			name: "Scattergun",
			fullName: "Strange Festivized Specialized Killstreak Flower Power Scattergun (Well-Worn)",
			id: "8621939549",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEMaQkUTxr2vTx8mMnvA-aHAfQ_ktk664MayTdinxVwPffiYghuZgHPUPUPDKIF4w3tG3MN7sJwQN6g8vVRf1q9sIfPMuZ-OdlLTMnVXqWEZQD66k5uhvAILpeN8n7q2y67aToORVO1rUMA3uS3/",
			tradable: true,
			craftable: true,
			quality: 11,
			texture: 72,
			wear: 4,
			festivized: true,
			killstreak: 2,
			defindex: 200,
			level: -1,
			classes: ["Scout"],
			type: "primary",
			sheen: "Hot Rod",
			collection: "Pyroland Collection",
			grade: "Mercenary",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 13,
			quality: 15,
			name: "Scattergun",
			id: "8621939549",
			killstreak: 2,
			killstreak_sheen: 7,
			festivized: true,
			texture: 72,
			wear: 4,
			strange: true,
		},
	},
	{
		title: "Skill Gotten Gains Taunt: The Skating Scorcher",
		input: {
			name: "Taunt: The Skating Scorcher",
			fullName: "Skill Gotten Gains Taunt: The Skating Scorcher",
			id: "12507393115",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEfbRIfSST2sD18m8PnGfuCD98TmNUn5phQywlnkBN8Ma3mZDI2IlOXUvJfDaZsoVi_W3dmv5VhBYTj8utSKg6-4YHEMbAvZt4fAYCODXraPvQv/",
			tradable: true,
			craftable: true,
			quality: 5,
			effect: 3007,
			defindex: 30919,
			level: 96,
			classes: ["Pyro"],
			type: "taunt",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 30919,
			quality: 5,
			name: "Taunt: The Skating Scorcher",
			id: "12507393115",
			unusual: 3007,
		},
	},
	{
		title: "Non-Craftable Unusual Taunt: Yeti Punch Unusualifier",
		input: {
			name: "Unusualifier",
			fullName: "Non-Craftable Unusual Taunt: Yeti Punch Unusualifier",
			id: "12507264002",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdEH9myp0du1AHE66AL6lNU5Fw_2yIWtaMjIpQmjAT3G9DJDbHxHF5bNp8LcXFyDr3oPCKGTqvPGSQLHjcTVg6TrNWY2_a_WCm4LuWQjuYEuF4QVwFe_EGpjJLa8vfIVJjg5FSpmLpqFwtQ0ZmIZAWNga2zSUsKex4mG9FcJtEwHmnJ_uQhVJidkNqWq6-C-vDAMiknS86VBpnCfFaJNLBtSHo-IGoN6CLdKtoOrIo6suSxEMTQ8gaV5gs9JNHqZn39QwQP9ttHQ5LQeF4ZzuHUazlwivMWee6a-YB5pQBAQ0SQki8nnRyWUA3qKeOw30xaus/",
			tradable: true,
			quality: 5,
			target: "Taunt: Yeti Punch",
			defindex: 9258,
			targetDefindex: 1182,
			craftable: false,
			level: 5,
			classes: [],
			type: "TF_Unusualifier",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 9258,
			quality: 5,
			name: "Unusualifier",
			id: "12507264002",
			craftable: false,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			target_def_index: 1182,
		},
	},
	{
		title: "Foppish Physician Strangifier Chemistry Set Series #2",
		input: {
			name: "Chemistry Set",
			fullName: "Non-Tradable Foppish Physician Strangifier Chemistry Set Series #2",
			id: "12507256108",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIYwkCSQn3uyxKh8bZBvuYN-wBid0wq8hXjW49lVl_NrC2ZjFjJlPHV6FcDPRj8Am1Cn5i6pE3DIfuoOxReV_x9NyRdNFoUKY/",
			craftable: true,
			quality: 6,
			target: "Foppish Physician",
			output: "Strangifier",
			outputQuality: 6,
			itemNumber: {
				type: "series",
				value: 2,
			},
			defindex: 20005,
			outputDefindex: 5661,
			targetDefindex: 878,
			level: 5,
			classes: [],
			type: "TF_ItemDynamicRecipeTool",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 20000,
			quality: 6,
			name: "Chemistry Set",
			id: "12507256108",
			tradable: false,
			never_tradable: false,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			item_number: 2,
			output_item: {
				item: {
					def_index: 5661,
					quality: 6,
					name: "Strangifier",
					usable: true,
					max_uses: 1,
					remaining_uses: 1,
					target_def_index: 878,
				},
			},
		},
	},
	{
		title: "Third Degree Strangifier",
		input: {
			name: "Strangifier",
			fullName: "Non-Tradable Third Degree Strangifier",
			id: "12507257164",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdEH9myp0du1AHE66AL6lNU5Fw_2yIWtaMjIpQmjATy1FSOCXHyXxkd-FoPczUxQDEreOfG3G5PWeUenaKRQ49SeVWZ2yI_2Cs5OSdFGzMFekoQ19ReqNS9GZPOpvcPgx9itAdomi_xntlTkt4PJceJUmyx3NCDqV0lXFcc5hXj32tcZW2zF9vaFhuWbjxD-GVbu7skSIkQx1vH7ZLJMvM7Cjo_JfnM6rRIKFkO690sNaTxVccSMQjWZgwzo1PuKH-uh9EbsZtSAtMR7t_ZG_VVfjgkX3NWOqzN-AK4pRWUgtMSxq-mCB7CRsrvfqIdE0e53GjJztD/",
			craftable: true,
			quality: 6,
			target: "Third Degree",
			defindex: 5661,
			targetDefindex: 593,
			level: 5,
			classes: [],
			type: "TF_StrangifierTool",
			parts: [],
			spells: [],
			marketable: true,
			commodity: true,
		},
		expected_output: {
			def_index: 5661,
			quality: 6,
			name: "Strangifier",
			id: "12507257164",
			tradable: false,
			never_tradable: false,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			target_def_index: 593,
			output_item: {
				def_index: 593,
				quality: 11,
			},
		},
	},
	{
		title: "The Patriot Peak (painted)",
		input: {
			name: "Patriot Peak",
			fullName: "Patriot Peak",
			id: "8621939024",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdEH9myp0erksICfSMfqIdEs5nqWSMU5OD2IwIlnYPyihXOjLx2Sk5MbUqMcbBnQz4ruyeU3Dya2aREDHYCExhEvcxdT2IpVz5tK_DFybOEOotQ1gNfKIA8jZJac_dahI-1Y9frmDgkkUtSk4pdJMfdQy4nSAQf60rz29jIiWT/",
			tradable: true,
			craftable: true,
			quality: 6,
			isUniqueHat: true,
			defindex: 30743,
			level: 42,
			classes: ["Scout", "Sniper", "Soldier", "Demoman", "Medic", "Heavy", "Pyro", "Spy", "Engineer"],
			type: "misc",
			collection: "Tough Break Cosmetics Collection",
			grade: "Mercenary",
			paint: "Australium Gold",
			paintDefindex: 5037,
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 30743,
			quality: 6,
			name: "Patriot Peak",
			id: "8621939024",
			paint: 10,
		},
	},
	{
		title: "The Sandman (spelled)",
		input: {
			name: "Sandman",
			fullName: "Sandman",
			id: "11508815507",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEIUxAeUh_ntgdBidzZAfOeD-VOz9s0vMAM3WRtwwcsNuGwZzJjc1SVUKQJDq1u91zvW3Uw7sQ7ANPm8fUWJ1sZuDp64A/",
			tradable: true,
			craftable: true,
			quality: 6,
			isUniqueHat: true,
			defindex: 44,
			level: 15,
			classes: ["Scout"],
			type: "melee",
			parts: [],
			spells: ["Exorcism"],
			marketable: false,
			commodity: false,
		},
		expected_output: {
			def_index: 44,
			quality: 6,
			name: "Sandman",
			id: "11508815507",
			spells: [14],
		},
	},
	{
		title: "Nice Winter Crate 2014 #89",
		input: {
			name: "Nice Winter Crate 2014",
			fullName: "Nice Winter Crate 2014 Series #89",
			id: "8621938857",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEYYQ4CThbjqwdAmsnyCM3eWLFUpNY095dQlzM_l1V_bbSwNW5mJFWRU_YHCac7rF29UCFrsZ80UNbjrrpTeAW84YLYc-57YBRl02c/",
			tradable: true,
			craftable: true,
			quality: 6,
			itemNumber: {
				type: "crate",
				value: 89,
			},
			defindex: 5790,
			level: 13,
			classes: [],
			type: "Supply Crate",
			parts: [],
			spells: [],
			marketable: true,
			commodity: true,
		},
		expected_output: {
			def_index: 5790,
			quality: 6,
			name: "Nice Winter Crate 2014",
			id: "8621938857",
			item_number: 89,
		},
	},
	{
		title: "Night Owl Mk.II War Paint (Factory New)",
		input: {
			name: "War Paint",
			fullName: "Night Owl Mk.II War Paint (Factory New)",
			id: "8621940709",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEMaQkUTxr2vTx8mMnvA-aHAfQ_ktk664MayTdinxVwPffkYWNYexDHDPkLD6MF4w3tG3Z8v5JlDNPnp74AKg3ovIGXNeIsYtFETsOCX_GCMAz06EJpgqFaKpKB9jSvg3ocrKV5Cg/",
			tradable: true,
			craftable: true,
			quality: 15,
			texture: 114,
			wear: 1,
			defindex: 9536,
			level: -1,
			classes: [],
			type: "TF_PaintKitTool",
			collection: "Decorated War Hero Collection",
			grade: "Mercenary",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 9536,
			quality: 15,
			name: "War Paint",
			id: "8621940709",
			texture: 114,
			wear: 1,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
		},
	},
	{
		title: "Non-Craftable Killstreak Enforcer Kit",
		input: {
			name: "Killstreak Kit",
			fullName: "Non-Craftable Killstreak Enforcer Kit",
			id: "9954933795",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/IzMF03bi9WpSBq-S-ekoE33L-iLqGFHVaU25ZzQNQcXdEH9myp0du1AHE66AL6lNU5Fw_2yIWtaMjIpQmjATy1FFJDf64npiduBTNMrUxwC1-bGMGiyiO2LHdiCBTw49RLcMMW7brGGh5LyTEzjIR-p6QwhSePYCoXoJY56fZk9q1ehD-zjo2RYlS1Ahf8IXTxfqlyRdZ-5wjigfIpo90CT9Jordhl90MRs9W9euV7HCcYatkDl1HVo-S60eYIuD4Xi79c6iNanFMrh1O6di7NaO2FgTQ_4bTJg_2Jp5uZ_hsg58Z4kvHFtSF-B3M2-EV_zulXbKWbKzNrIB5pNYVllPG0a1nSJ9CBgovPDZbVlItmBmrPVjv1UHYg/",
			tradable: true,
			quality: 6,
			killstreak: 1,
			target: "Enforcer",
			defindex: 5726,
			targetDefindex: 460,
			craftable: false,
			level: 11,
			classes: [],
			type: "TF_KillStreakifierToolA",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 5726,
			quality: 6,
			name: "Kit",
			id: "9954933795",
			craftable: false,
			killstreak: 1,
			target_def_index: 460,
		},
	},
	{
		title: "Specialized Killstreak Mantreads Kit Fabricator",
		input: {
			name: "Specialized Killstreak Kit Fabricator",
			fullName: "Specialized Killstreak Mantreads Kit Fabricator",
			id: "11131585586",
			img: "https://steamcommunity-a.akamaihd.net/economy/image/fWFc82js0fmoRAP-qOIPu5THSWqfSmTELLqcUywGkijVjZULUrsm1j-9xgEbfggXWAjxsTdNicTZBvuYN-wBid0wq8MNjzRtlQcrZeCwZm5mIlOUVaFfWaI8pgq7CyRhvJYwA9W1rusHfw3x9NyRDoHCqNM/",
			tradable: true,
			craftable: true,
			quality: 6,
			target: "Mantreads",
			defindex: 20002,
			targetDefindex: 444,
			level: 5,
			classes: [],
			type: "TF_ItemDynamicRecipeTool",
			parts: [],
			spells: [],
			marketable: true,
			commodity: false,
		},
		expected_output: {
			def_index: 20002,
			quality: 6,
			name: "Fabricator",
			id: "11131585586",
			killstreak: 2,
			target_def_index: 444,
			output_item: {
				item: {
					def_index: 5726,
					quality: 6,
					name: "Kit",
					craftable: false,
					killstreak: 2,
					target_def_index: 444,
				},
			},
		},
	},
];
