export default [
	{
		title: "Strange Specialized Killstreak Australium Axtinguisher",
		input: {
			def_index: 38,
			quality: 11,
			name: "Axtinguisher",
			killstreak: 2,
			australium: true,
		},
		expected_output: "38;11;australium;kt-2",
	},
	{
		title: "Strange Festivized Specialized Killstreak Flower Power Scattergun (Well-Worn)",
		input: {
			def_index: 13,
			quality: 15,
			name: "Scattergun",
			killstreak: 2,
			festivized: true,
			texture: 72,
			wear: 4,
			strange: true,
		},
		expected_output: "13;15;w4;pk72;strange;kt-2;festive",
	},
	{
		title: "Skill Gotten Gains Taunt: The Skating Scorcher",
		input: {
			def_index: 30919,
			quality: 5,
			name: "Taunt: The Skating Scorcher",
			unusual: 3007,
		},
		expected_output: "30919;5;u3007",
	},
	{
		title: "Non-Craftable Unusual Taunt: Yeti Punch Unusualifier",
		input: {
			def_index: 9258,
			quality: 5,
			name: "Unusualifier",
			craftable: false,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			target_def_index: 1182,
		},
		expected_output: "9258;5;uncraftable;td-1182",
	},
	{
		title: "Foppish Physician Strangifier Chemistry Set #2",
		input: {
			def_index: 20000,
			quality: 6,
			name: "Chemistry Set",
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			item_number: 2,
			target_def_index: 878,
			output_item: {
				item: {
					def_index: 5661,
					quality: 6,
					name: "Strangifier",
					usable: true,
					max_uses: 1,
					remaining_uses: 1,
					target_def_index: 878,
				},
			},
		},
		expected_output: "20000;6;td-878;n2;od-5661;oq-6",
	},
	{
		title: "Third Degree Strangifier",
		input: {
			def_index: 5661,
			quality: 6,
			name: "Strangifier",
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
			target_def_index: 593,
			output_item: {
				def_index: 593,
				quality: 11,
			},
		},
		expected_output: "5661;6;td-593",
	},
	{
		title: "Nice Winter Crate 2014 #89",
		input: {
			def_index: 5790,
			quality: 6,
			name: "Nice Winter Crate 2014",
			item_number: 89,
		},
		expected_output: "5790;6;c89",
	},
	{
		title: "'Decorated War Hero' War Paint Mercenary Grade Keyless Case #113",
		input: {
			def_index: 18002,
			quality: 6,
			name: "'Decorated War Hero' War Paint Mercenary Grade Keyless Case",
			item_number: 113,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
		},
		expected_output: "18002;6;c113",
	},
	{
		title: "Night Owl Mk.II War Paint (Factory New)",
		input: {
			def_index: 9536,
			quality: 15,
			name: "War Paint",
			texture: 114,
			wear: 1,
			usable: true,
			max_uses: 1,
			remaining_uses: 1,
		},
		expected_output: "9536;15;w1;pk114",
	},
	{
		title: "Non-Craftable Killstreak Enforcer Kit",
		input: {
			def_index: 5726,
			quality: 6,
			name: "Kit",
			craftable: false,
			killstreak: 1,
			target_def_index: 460,
		},
		expected_output: "5726;6;uncraftable;kt-1;td-460",
	},
	{
		title: "Specialized Killstreak Mantreads Kit Fabricator",
		input: {
			def_index: 20002,
			quality: 6,
			name: "Fabricator",
			killstreak: 2,
			target_def_index: 444,
			output_item: {
				item: {
					def_index: 5726,
					quality: 6,
					name: "Kit",
					craftable: false,
					killstreak: 2,
					target_def_index: 444,
				},
			},
		},
		expected_output: "20002;6;kt-2;td-444;od-5726;oq-6",
	},
];
